### ISSUE TITLE
Toon East and West schedule at https://cnvideo.sercomkc.org/schedule/ consistently inncomplete since 21 August

### ISSUE THREAD

**Issue by pal1000** [SerCom-KC/cartoon-network-schedule#1]
Schedule jumps consistently for each day from 6am to 5pm for Toon East and 9am to 8pm for Toon West when using Eastern Time. This began on 21 August. This glitch also causes current link to fail if we are in the missing schedule interval of today.

**Comment by szescxz** [comment]
Thanks for the heads up, this should now be fixed on the website.
