### ISSUE TITLE
current button is not reliable anymore

### ISSUE THREAD

**Issue by pal1000** [SerCom-KC/cartoon-network-schedule#4]
Depending on channel is either working properly or suck between Oct. 16 and 20.

**Comment by pal1000** [comment]
This was  somehow fixed in early November.

**Comment by szescxz** [comment]
Workaround implemented at https://github.com/SerCom-KC/cartoon-network-videos/commit/e8cdc21aabe057bd1b8836e81692420a4ba9bcb8. Should be scrolling to the correct showing now.
WarnerMedia's system is pretty broken I guess...
